### ISSUE TITLE
Removal of libsodium breaks custom component

### ISSUE THREAD

**Issue by derjoerg** [home-assistant/docker-base#187]
Hi,

I hope this is the right place for this issue.

With the following commit (https://github.com/home-assistant/docker/commit/e926373887e789b48945e14118de9134da1be195) the package libsodium was removed from the HA-docker images.
This now breaks the custom component free@home (https://github.com/jheling/freeathome/issues/130).

Is it possible to re-add this package to the docker-images?

**Comment by frenck** [comment]
We won't be re-adding it, as we don't use it ourselves. We try to keep the docker images tailored towards running Core without shipping unneeded packages.

../Frenck

**Comment by frenck** [comment]
No we have methods for doing that.

Please note, we do offer the possibility to run custom integration, The Home Assistant project doesn't support them.

../Frenck

**Comment by Gersh1970** [comment]
Well I don’t know why this is not an official integration and why it never reached that status. 
But bear in mind that with this integration home assistant connects with the free@home home control system of Busch Jaeger. A well known manufacturer of switches, dimmers, etc. A big Dutch building firm ‘Heijmans’ has used this system in houses since 2017 and it connects with Philips Hue, Sonos and google assistant and without this integration it makes no sense using home assistant as then you cannot control light, dimmers, etc. 

So I can understand removing the library but you should be aware with this you take a step in moving people away from home assistant and that is a pity as home assistant is such a beautiful product.

**Comment by frenck** [comment]
@Gersh1970 It's a custom integration. The Home Assistant project is very clear on the support of those (we don't support them). We welcome an integration moving into the core to get core support.

Nevertheless, the integration library used should probably move to use pynacl. Nevertheless, that is up to the custom integration maintainers.

../Frenck

**Comment by Gersh1970** [comment]
@frenck Of course we all understand that you cannot support a custom integration and want the keep the system clean and remove unused libraries. However it was removed without notice and not even mentioned in the release notes.
As there seems to be no active development, moving to pynacl can take some time. Having a workaround by manually adding the library works for me, but that's not easy for everyone. So people with the Busch Jaeger system will move away from Home Assistant as they cannot control there lights, thermostat anymore and that is a pity as it is such a beautiful product.

So we just kindly ask to re-add the library :)
Keep up the good work!
